---
# Site Settings
locale                   : "en-US"
title                    : "Micaela Matta"
title_separator          : "|"
name                     : "Micaela Matta"
description              : ""
url                      : #"www.micaelamatta.com"
baseurl                  : # the subpath of your site, e.g. "/blog"
repository               : micaela-matta/micaelamatta.com
teaser                   : "/images/ionscapes_bare.png"
timezone: UTC


# Site Author
author:
  name             : "Micaela Matta"
  avatar           : "/images/profile_photo.png"
  bio              : ""
  location         : "Liverpool, UK"
  email            : "micaela.matta@liverpool.ac.uk"
  uri              :
  flickr           :
  github           : "micaela-matta"
  twitter          : "micaelamatta"
  linkedin         : "micaela-matta-a691784a" #(the last part of your profile url, e.g. https://www.linkedin.com/in/john-doe-12345678)
  links:
    - label: '<a class="twitter-timeline" style="font-size:100%;" href="https://twitter.com/micaelamatta?ref_src=twsrc%5Etfw">Tweets by micaelamatta</a> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>'
      icon: "twitter"
      url: "www.twitter.com/" 


plugins:
  - jekyll-archives

permalink: "/:title/"
version: v1.2.0
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
sass:
  style: :expanded
gems:
- jekyll-sitemap
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock
- LICENSE
- README.md
- CNAME
remote_theme: mmistakes/minimal-mistakes@4.12.0
minimal_mistakes_skin: "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum" "sunrise"
og_image: /images/myownimage.jpg
#header links and categories
# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
      read_time: false
      comments: # true
      share: false
      related: false
# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
