---
# Site Settings
locale                   : "en-US"
title                    : "Micaela Matta"
title_separator          : "|"
name                     : "Micaela Matta"
description              : "my personal website"
url                      : "https://micaela-matta.github.io"
baseurl                  : # the subpath of your site, e.g. "/blog"
repository               : micaela-matta/micaela-matta.github.io
teaser                   : "images/myownimage.jpg"
timezone: UTC


header:
  overlay_image: images/myownimage.jpg
  overlay_filter: 0.5 # same as adding an opacity of 0.5 to a black background
  caption: "I also take photos. [**Unsplash**](http://a--simple--life.tumblr.com)"

# Site Author
author:
  name             : "Micaela Matta"
  avatar           : "images/Nyan_cat_250px_frame.PNG"
  bio              : #"computational chemist by day, blues dancer by night, bike commuter in between."
  location         : "Chicago, IL"
  email            : "micaela.matta@northwestern.edu"
  uri              :
  flickr           :
  github           : "micaela-matta"
  gitlab           :
  linkedin         : "micaela-matta-a691784a" #(the last part of your profile url, e.g. https://www.linkedin.com/in/john-doe-12345678)
  tumblr           : #"http://a--simple--life.tumblr.com"

permalink: "/:title/"
version: v1.2.0
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
sass:
  style: :expanded
gems:
- jekyll-sitemap
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock
- LICENSE
- README.md
- CNAME
remote_theme: mmistakes/minimal-mistakes@4.12.0
minimal_mistakes_skin: "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum" "sunrise"

#header links and categories
main:
  - title: "Resume"
    url: pages/resume.md
  - title: "Publications"
    url: https://scholar.google.com/citations?user=o4zoWRQAAAAJ&hl
  - title: "Teaching"
    url: pages/teaching.md
  - title: "Institutional page"
    url: https://sites.northwestern.edu/schatz/micaela-matta/

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: # true
      share: true
      related: true
