---
# Site Settings
locale                   : "en-US"
title                    : "Micaela Matta"
title_separator          : "-"
name                     : "unicorn fluff."
description              : "fluffy unicorn."
url                      : # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
baseurl                  : # the subpath of your site, e.g. "/blog"
repository               : # GitHub username/repo-name e.g. "mmistakes/minimal-mistakes"
teaser                   : # path of fallback teaser image, e.g. "/assets/images/500x300.png"
timezone: UTC

collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true

# Site Author
author:
  name             : "Micaela Matta"
  avatar           : "images/Nyan_cat_250px_frame.PNG"
  bio              : "computational chemist by day, blues dancer by night, bike commuter in between."
  location         : "Chicago, IL"
  email            : "micaela.matta@northwestern.edu"
  uri              :
  flickr           :
  github           : "micaela-matta"
  gitlab           :
  linkedin         : "micaela-matta-a691784a" #(the last part of your profile url, e.g. https://www.linkedin.com/in/john-doe-12345678)
  tumblr           :

permalink: "/:title/"
version: v1.2.0
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
sass:
  style: :expanded
gems:
- jekyll-sitemap
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock
- LICENSE
- README.md
- CNAME
remote_theme: mmistakes/minimal-mistakes@4.12.0
minimal_mistakes_skin: "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum" "sunrise"

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: # true
      share: true
      related: true
